version: '2'
services:
  cd:
    mem_limit: 512m
    labels:
      - convox.port.443.protocol=https
      - convox.health.path=/health
      - convox.health.timeout=60
    build:
      context: .
      args:
        - CONVOX_ACCESS_TOKEN
    ports:
      - 80:3000
      - 443:3000
    environment:
      - RACK_ENV
      - CONVOX_ACCESS_TOKEN